services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: chat_postgres
    environment:
      POSTGRES_PASSWORD: toha
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NestJS Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat_server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:toha@postgres:5432/chatdb?schema=public
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./server:/app
      - /app/node_modules

  # Next.js Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat_client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
    depends_on:
      - server

volumes:
  postgres_data:
